//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstatusAceros
    {
        public int id { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Responsable { get; set; }
        public string Rollo { get; set; }
        public string Hora { get; set; }
        public System.DateTime fecha_captura { get; set; }
        public string usuario_captura { get; set; }
    }
}
