//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPM.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPMEntities : DbContext
    {
        public PPMEntities()
            : base("name=PPMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estatus> Estatus { get; set; }
        public virtual DbSet<Prensas> Prensas { get; set; }
        public virtual DbSet<administradores> administradores { get; set; }
        public virtual DbSet<EstatusPrensa> EstatusPrensa { get; set; }
        public virtual DbSet<Programa> Programa { get; set; }
        public virtual DbSet<EstatusAceros> EstatusAceros { get; set; }
    }
}
